CREATE DATABASE ejercicio9TA14;
USE ejercicio9TA14;
CREATE TABLE CIENTIFICOS(
DNI VARCHAR(8),
NOM_APELS VARCHAR(255),
PRIMARY KEY (DNI)
);
CREATE TABLE PROYECTO(
ID CHAR(4),
NOMBRE VARCHAR(255),
HORAS INT,
PRIMARY KEY (ID)
);
CREATE TABLE PERTENECE_A(
CIENTIFICO VARCHAR(8),
PROYECTO CHAR(4),
PRIMARY KEY (CIENTIFICO, PROYECTO),
FOREIGN KEY (CIENTIFICO) REFERENCES CIENTIFICOS(DNI)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (PROYECTO) REFERENCES PROYECTO(ID)
ON DELETE CASCADE ON UPDATE CASCADE
);